### ISSUE TITLE
non-historical agents

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#102]
I'm working with DILA on the migration of their dataset. The property that cannot be migrated is the 'historical' boolean for persons. While we could imagine having such a boolean in the ontology, I think  it might be helpful to think a bit more broadly about this. There are many types of agent entities that sometimes overlap:
- Bodhisattvas
- Yidams
- Fictional characters
- Being of different realms (animals, gods, nagas, etc.)

I'm really unsure how to encode that, mabe having something like:

```
:Entity
    :Agent          (all agents)
        :Person    (historical)
```

and then associate different... types ? roles? to agents... wdyt?

**Comment by xristy** [comment]
I've added, as you suggest, ```:Agent``` and a top-level hierarchy of sub-classes that we can extend downward to accommodate various distinctions such as you've listed above:

    :Entity
        :Agent
            :SingleAgent
                :Person 
                :AhistoricalAgent
            :Organization
                :Corporation

I would think that we would want to migrate the various ```:Topic```s that represent different sorts of ```:AhistoricalAgent```.

See also #103.

**Comment by eroux** [comment]
perfect thanks! I agree we want to migrate some topics yes. I'll think of some properties we could use to represent the information recorded in the Jataka database
