### ISSUE TITLE
using SHACL?

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#11]
I've found what I was looking for the other day in terms of validation: SHACL. The [recommendation](https://www.w3.org/TR/shacl/) has just been released (last week), and there's a [Java implementation](https://github.com/TopQuadrant/shacl). There is also a [pure JavaScript implementation](https://github.com/TopQuadrant/shacl-js). It looks quite interesting as it is really made for validation (unlinke OWL reasoners) and is quite flexible (you can express shapes as SPARQL queries, you can require some strings to follow some regexp, etc.).

Something interesting (and a bit confusing at first) is that there is a [spec to express shapes in JavaScript](https://www.w3.org/TR/shacl-js/), but the Java implementation seems to handle it too, it's not specific to JavaScript implementations.

A [note on advanced features](https://www.w3.org/TR/shacl-af/) also exists... I cannot say I understand everything, but it seems worth inspecting...

**Comment by xristy** [comment]
I agree SHACL is very interesting. Here are some links I've found interesting:

[Karen Coyle comments](http://kcoyle.blogspot.com/2015/10/shacl-shapes-constraint-language.html)

[shapes mailing list archive](https://lists.w3.org/Archives/Public/public-rdf-shapes/)

[SHACL shape repository](https://github.com/AKSW/shacl-shapes)

[Discovery service for SHACL shapes](https://github.com/AKSW/discover-shacl-shapes)

**Comment by eroux** [comment]
I think we're on tracks for that, let's close it and open more specific issues as they appear
