### ISSUE TITLE
bdrc bcp47 code for :Language

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#112]
I have an engineering problem that I think can be solved by adding a useful property to the ontology:

When a work has multiple labels/titles in multiple languages ([example](https://www.tbrc.org/#!rid=W1KG14618)), I need to select one of these titles for the MARC export in a (relatively) consistent way. An idea is to privilege the title that is in the main language of the book's content (in this case Tibetan). This technique would also be used in the iiif presentation API to select a title.

Note that it would be useful to do that for persons too but I don't think we can do that easily...

Anyways, a way to do that would be to indicate the initial part of the BCP47 tag that BDRC is using to tag the strings in a particular language. For instance we would have

```
bdr:LangBo a :Language ;
    :langBCP47BDRCPrefix "bo" .
```

so that I can select the titles/labels strings that have a lang tag starting with "bo". wdyt?

**Comment by eroux** [comment]
well, thinking about it again, if it's attached to the language, it's not bdrc specific, so just `:langBCP47Lang` is probably enough... (the final `Lang` is to indicate that we just take the lang part of the BCP47 tag, not the rest (script, transliteration, etc.)

**Comment by xristy** [comment]
Closed via https://github.com/buda-base/owl-schema/commit/3fce97d4153cfc688aa705b6b81da76e9724a04a
