### ISSUE TITLE
new traditions / schools

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#119]
To fully finish the translation of DILA data into RDF, we also need to associate persons with different traditions. For that we need two new elements:
- a property linking a `bdo:Person` to a `bdo:Tradition`, maybe by changing `:personOfSect`'s range?
- three individuals:
   * `"禪宗"@zh-Hant , "Zen school"@en`
   * `"天台宗"@zh-Hant , "Tiantai School"@en`
   * `"三階教"@zh-Hant , "Three Stages School"@en`

**Comment by xristy** [comment]
should have also mentioned that the property ```:personOfTradition``` mapping ```:Person``` to ```:Tradition```
