### ISSUE TITLE
Global is auth

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/owl-schema#124]
in global.ttl we have:

```
global:
  a owl:Ontology ;
  owl:imports adm: ;
  owl:imports aut: ;
```
but aut already imports adm (which imports bdo)

so global is the same as auth (that imports adm which imports bdo)

Is global used somewhere? What should we do with it (from an ontology service perspective)?

**Comment by xristy** [comment]
I do not know of any uses of global.ttl. I'm delighted to remove it. Let me know.

**Comment by MarcAgate** [comment]
Unless someone is using it (I doubt someone is), I suggest we remove it, yes !

**Comment by xristy** [comment]
Indeed, I will remove in the morning. 

Also the dropdown lists for view and browse on ldspdi should at least be sorted, better would be a small 2 char indent for sub-dirs and files etc

**Comment by MarcAgate** [comment]
I am not sure about keeping "individual ontologies" in the drop down list... I am thinking of linking Individuals to their class display page (as here : [http://purl.bdrc.io/ontology/core/TibetanLineageType](http://purl.bdrc.io/ontology/core/TibetanLineageType)). This shouldn't be too big of an issue.

**Comment by xristy** [comment]
I'd prefer to config so that just adm, bdo, and aut are listed - i.e.,agree we don't need all the various sub files  in the dropdown. I do think it would make sense to display the owl:Ontology resource w/ its owl:imports that are clickable to allow navigating among ontology modules

**Comment by MarcAgate** [comment]
We now have links to imported ontologies on each Ontology home page. Closed
