### ISSUE TITLE
indication of the terma nature of a text

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#126]
For some texts (imported from EAP), we know that they are terma but we don't know who the terton is (or at least we can't spend too much energy searching it). In that case what's the best way to indicate that the text is a terma?

I'm thinking of

```
:creatorTerton  bdr:UNKNOWN_Person
```

?

**Comment by xristy** [comment]
Using `bdr:UNKNOWN_Person` is indeed the solution.

**Comment by eroux** [comment]
ok
