### ISSUE TITLE
TemporarilyRestricted vs. RestrictedTemporarily

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/owl-schema#130]
in [http://purl.bdrc.io/resource/W1KG24968.ttl](http://purl.bdrc.io/resource/W1KG24968.ttl) we have adm:access    bdr:AccessTemporarilyRestricted ;

but [http://purl.bdrc.io/resource/AccessTemporarilyRestricted.ttl](http://purl.bdrc.io/resource/AccessTemporarilyRestricted.ttl) fails while [http://localhost:8080/resource/AccessRestrictedTemporarily.ttl](http://localhost:8080/resource/AccessRestrictedTemporarily.ttl) succeeds

**Comment by eroux** [comment]
It's probably a problem in xmltold... I think it would be faster to run a small SPARQL query changing the triples than running a new migration though

**Comment by MarcAgate** [comment]
the following update request did the job in fuseki dataset:

DELETE {graph ?s {?s adm:access bdr:AccessTemporarilyRestricted .}}
INSERT {graph ?s {?s adm:access bdr:AccessRestrictedTemporarily .}}
where { 
{ ?s adm:access bdr:AccessTemporarilyRestricted .}
}

**Comment by eroux** [comment]
Great, thanks!
