### ISSUE TITLE
Implementing Editing status 

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/owl-schema#131]
It looks like we don't yet have a way to signify the edit status of a given resource. This might be achieved through an adm:editStatus property and a couple of individuals (for instance: Editing, Provisional, AwaitingValidation, Released, etc...)
WDYT ?

EDIT: I just realized that some statuses already exist as Individuals of adm:Status.  Shoudn't we separate edit statuses from statuses related to field operations (like scanning, acquiring, and so on ?)

**Comment by eroux** [comment]
What you're proposing is indeed the intent of the `adm:status` property. Separating the data about the images from the data about the record seems like a good idea, but it shouldn't block you
