### ISSUE TITLE
Property bdo:workHasItem should suffice

### ISSUE THREAD

**Issue by xristy** [buda-base/owl-schema#136]
I don't think we need the subProperties: `bdo:workHasItemImageAsset` and so on.

It should suffice to refer to: `bdo:workHasItem/rdf:rtype`.

If one wants the `:ItemImageAsset` for a `:Work`, `?work`, then:

```
?work :workHasItem ?item . 
?item rdf:type :ItemImageAsset .
```

**Comment by xristy** [comment]
and the same for the inverse `:itemForWork`

**Comment by eroux** [comment]
This is fine but a few queries rely on it so they should be changed as well

**Comment by xristy** [comment]
Keeping this issue open until lds-queries dependencies are resolved
