### ISSUE TITLE
replacing xsd:integer with xsd:gYear

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#149]
For `bdo:AnyDate`, we should use [gYear](https://www.w3.org/TR/xmlschema11-2/#gYear) instead of integer (and in the xmltold as well)

**Comment by eroux** [comment]
note that we could also extend the definition of `bdo:AnyDate` to also allow gMonth, gDay, gYearMonth, etc.

**Comment by xristy** [comment]
closed via [18a2e82](https://github.com/buda-base/owl-schema/commit/18a2e827f3b8d8a810153d69e2ec8516b8cba355) with [xmltoldmigration 101](https://github.com/buda-base/xmltoldmigration/issues/101)
