### ISSUE TITLE
offset / lithography

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#155]
In importing data from the NGMPP catalog, I stumble upon a print method that they indicate

> lithograph, i.e. referring to the modern lithographs printed in India on the basis of a manuscript or xylograph

I'm really not familiar with that kind of technology... the wikipedia pages seem to say that [offset printing](https://en.wikipedia.org/wiki/Offset_printing) can use [lithography](https://en.wikipedia.org/wiki/Lithography), I guess that's what's being referred to... but I don't know the best way to refer to the print process... Anyways, we should add one individual for that.

**Comment by xristy** [comment]
fixed in [fc9deb1](https://github.com/buda-base/owl-schema/commit/fc9deb1a9151e88c8bd416dd9395ad398c8f7497)
