### ISSUE TITLE
where does bdg:shapesSchema in  newcorerw come from?

### ISSUE THREAD

**Issue by xristy** [buda-base/owl-schema#167]
I notice in ```newcorerw``` that there is a ```bdg:shapesSchema``` that appears to be a copy of ```bdg:ontologySchema```.

Where did it come from?

**Comment by eroux** [comment]
I have no clue, @MarcAgate is it a side effect of the code at some previous stage of development?

**Comment by MarcAgate** [comment]
This issue has been fixed in ldspdi. The graph name came from editor-templates ont-policy.rdf that was overwriting default graph name in one class of ldspdi.
Now, do we want to store shapes data in that graph (shapesSchema) in fuseki newcorerw ?

**Comment by xristy** [comment]
I just pushed a change to ```editor-templates/ont-policy.rdf``` to ignore the core bdo.ttl import in the shapes files with the intent that when the ```http://purl.bdrc.io/graph/shapesSchema``` ontGraph is built it won't be populated from ```core/bdo.ttl``` and should have just the shapes triples in templates/core ...

If this works as I expect then this approach could be used to create separate graphs for taxonomies if they're in a distinct repo as @eroux is considering in issue #166.

**Comment by MarcAgate** [comment]
Yes, that's part of the fix. The shapes currently available from ldspdi-dev are loaded from editor-templates already, at startup. I just have now to set up a webhook in github and a callback endpoint in ldspdi and everything should be fine. 
By doing so we will end up with a  shapesSchema graph on newcorerw containing shapes coming from editor-templates and updated each time there is a change in editor-templates.

**Comment by MarcAgate** [comment]
We have now the whole thing working as explained above. A Web-hook has been set in editor-templates repo. All tests passed.

**Comment by eroux** [comment]
wonderful, thanks!
