### ISSUE TITLE
encoding collections

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#174]
Now that we have the minimal thing with the products, I think it would be good to encode collections too, in a more detailed way (I have some NGMPP data to encode with it). The main use cases are:
- household collections: 
   * collection of mister X, in village Y
   * collection of lama X in monastery Y
- institutional collections: 
   * collection of monastery X
   * national archives of X
   * special collection X in Library Y (ex: Stein collection at BL, Tucci collection at IsIAO, etc.)

I think there could be a new "Collection" entity (I would almost say it could be a subclass of product but I don't really see it leaving in the `bda:` namespace...). And a property linking either `Instance` (for manuscripts) or `Item` (the more general case) and collection. A collection could have two properties (in addition to the labels), `:agent` and `:place`? wdyt @xristy ?

**Comment by eroux** [comment]
here's an alternative: digital collection could be a subclass of collection and could replace products (as a generalization of this aspect of products, there may be other aspects of products not cover by collections?)

**Comment by xristy** [comment]
How related to collection skos:scheme idea?

**Comment by xristy** [comment]
`bdo:Collection` class hierarchy will replace `bda:Product`. The following classes and properties are added:
```
bdo:Collection
  rdfs:subClassOf bdo:Entity ;
.
bdo:HouseholdCollection
  rdfs:subClassOf bdo:Collection ;
.
bdo:InstitutionalCollection
  rdfs:subClassOf bdo:Collection ;
.
bdo:MonasticCollection
  rdfs:subClassOf bdo:InstitutionalCollection ;
.
bdo:ArchivesCollection
  rdfs:subClassOf bdo:InstitutionalCollection ;
.
bdo:SpecialCollection
  rdfs:subClassOf bdo:InstitutionalCollection ;
.
bdo:collectionMember
  rdfs:domain bdo:Collection ;
  rdfs:range bdo:BiblioEntity ;
  owl:inverseOf bdo:inCollection ;
.
bdo:collectionAgent
  rdfs:domain bdo:Collection ;
  rdfs:range bdo:Agents ;
.
bdo:collectionPlace
  rdfs:domain bdo:Collection ;
  rdfs:range bdo:Place ;
.
bdo:inCollection
  rdfs:domain bdo:BiblioEntity ;
  rdfs:range bdo:Collection ;
  owl:inverseOf bdo:collectionMember ;
.
```
Note that `bdo:CollectionInstitution` exists and is unused hence deprecated.

Also `adm:productHasDigitalInstance` is deprecated in favor of `bdo:collectionMember`.

**Comment by eroux** [comment]
great, thanks! I'll use that for the various partner collections, starting with NGMCP
