### ISSUE TITLE
Use secure URIs for ontologies/namespaces

### ISSUE THREAD

**Issue by rjyounes** [buda-base/owl-schema#178]
E.g., https://purl.bdrc.io/ontology/core rather than http://purl.bdrc.io/ontology/core.

**Comment by eroux** [comment]
Ah well, this is an issue that I see debated from times to times with both sides having good arguments (and sometimes strong emotions)... Unless there's a very strong case, I think we'll stick with http for the namespaces. If you use https for fetching that will work of course

**Comment by rjyounes** [comment]
OK.
