### ISSUE TITLE
removing deprecated properties

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#186]
We have a lot of deprecated properties, I think we could delete them... @rjyounes as an expert and also our main non-BDRC user, what do you think?

**Comment by rjyounes** [comment]
The Semantic Arts policy is to remove deprecated properties when a new major version is released. We are using [Semantic Versioning](https://semver.org) and define major, minor, and patch changes as documented in our [change and release management doc](https://github.com/semanticarts/gist/blob/develop/docs/ChangeAndReleaseManagement.md) (see section Versions and Version Numbering).  Thus any deprecated terms could be removed in your next major release, 4.0.0. If  you don't plan on doing any intermediate minor or patch releases before that, they could be removed now.

**Comment by eroux** [comment]
Ok excellent, thanks!
