### ISSUE TITLE
changing workRef pattern

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#86]
Discussing possible adjustments in the ontology for [CBC@](https://dazangthings.nz/cbc/), I think it would be easier to change the `bdo:workRefXXX` pattern a little. Instead of having:

```
bdr:W123 bdo:workRefTaisho "T0125" .
```

we could have instead:

```
bdr:W123 bdo:workRef [
      bdo:refType bdr:RefTaisho
      rdf:value "T0125"
   ] .
```

we would define some reference systems in the ontology, but any other project could also define theirs, so that we don't have to add new properties all the time. There are a lot of catalogs with identifiers out there (all the Dunhuang catalogs, many canonical catalogs in other languages, etc.), and adding them all would probably clutter the core ontology and make it less future-proof.

**Comment by xristy** [comment]
Great change! So ``bdr:RefTaisho`` would be an instance of class, ``bdo:WorkRef``.

**Comment by eroux** [comment]
that sounds about right

**Comment by xristy** [comment]
per skype chat we'll let this bake for now
